language: c

sudo: required
dist: trusty

compiler:
  - gcc

script:
  - wget https://www.libsdl.org/release/SDL2-2.0.8.tar.gz -O - | tar -xz
  - cd SDL2-2.0.8 && CC=gcc-7 ./configure --prefix=/usr && make -j2 && sudo make install && cd ..
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=On -DUSE_DYNAMIC_LIBASS=On -DCMAKE_C_COMPILER=/usr/bin/gcc-7 . 
  - build-wrapper-linux-x86-64 --out-dir bw-output make && sonar-scanner

notifications:
  email: false

addons:
  sonarcloud:
    organization: "katajakasa-github"
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - sourceline: 'ppa:george-edison55/cmake-3.x'
    - sourceline: 'ppa:jonathonf/ffmpeg-3'
    packages:
    - cmake
    - gcc-7
    - libass-dev
    - libavcodec-dev
    - libavformat-dev
    - libswresample-dev
    - libswscale-dev
    - libavutil-dev

cache:
  directories:
    - '$HOME/.sonar/cache'
